'': 'home/index'
'review/([0-9]+)': 'reviews/view/$1'
'write': 'reviews/write'

'signup': 'security/signup'
'login': 'security/login'
'logout': 'security/logout'

'profile/([0-9]+)': 'profile/index/$1'

'admin': 'admin/index'
'admin/users': 'admin/users'
'admin/reviews': 'admin/reviews'

'comment': 'comment/comment'