# HomeController
'': 'home/index'

# ReviewsController
'review/([0-9]+)': 'reviews/view/$1'
'write': 'reviews/write'

# SecurityController
'signup': 'security/signup'
'login': 'security/login'
'logout': 'security/logout'

# ProfileController
'profile/([0-9]+)': 'profile/index/$1'
'profile/edit' : 'profile/edit'

# AdminController
'admin': 'admin/index'
'admin/users': 'admin/users'
'admin/reviews': 'admin/reviews'

# CommentController
'comment': 'comment/comment'

# api
'api/get/reviews' : 'reviews/getReviews'