# HomeController
'': 'home/index'

# ReviewsController
'review/([0-9]+)': 'reviews/view/$1'
'write': 'reviews/write'

# SecurityController
'signup': 'security/signup'
'login': 'security/login'
'logout': 'security/logout'

# ProfileController
'profile/([0-9]+)': 'profile/index/$1'
'profile/edit' : 'profile/edit'
'follow/([0-9]+)': 'profile/follow/$1'
'unfollow/([0-9]+)': 'profile/unfollow/$1'
'profile/load-avatar': 'profile/loadAvatar'

# AdminController
'admin': 'admin/index'
'admin/users': 'admin/users'

'admin/users/view/([0-9]+)': 'admin/viewUser/$1'
'admin/users/delete/([0-9]+)': 'admin/deleteUser/$1'

'admin/reviews': 'admin/reviews'
'admin/reviews/view/([0-9]+)': 'admin/viewReview/$1'
'admin/reviews/delete/([0-9]+)': 'admin/deleteReview/$1'

# CommentController
'comment': 'comment/comment'

# LikeController
'like' : 'like/like'
'unlike' : 'like/unlike'

# api
'api/get/reviews' : 'reviews/getReviews'